version: '3.8'

services:
  postgres:   # this will become one container, jitni service utni container
    image: postgres:13  
    container_name: postgres 
    environment:
      POSTGRES_DB: pulse
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5435:5432"  # host:container  
    networks:
      - backend
    volumes:
      - postgres-data:/var/lib/postgresql/data    

  redis:    # this will become another container
    image: redis:latest
    container_name: redis
    ports:
      - "6380:6379"  # host:container
    networks:
      - backend

  app:
    image: ravin110/rent-mate-backend-app:latest # 👈 name your image here
    container_name: misogi-ai
    ports:
      - "8082:8080"  # host:container
    depends_on:
      - postgres
      - redis
    networks:
      - backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/pulse
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379

volumes:
  postgres-data:

networks:
  backend: